---
- name: Include Vars files
  include_vars: "roles/debug-api/vars/dev_api.yml"
  no_log: true

- name: Fetch the API information
  uri:
   url: "http://restapi.adequateshop.com/api/users?page=1"
   method: GET
   body_format: json
   return_content: yes
   headers:
    Authorization: "{{ api_token }}"
    Content-Type: "application/json"
    Accept: "*/*"
   status_code: 200
  register: store_result
  no_log: True

- name: Display the result
  debug:
    var: store_result.json

- name: Set facts
  set_fact:
    jsondata: "{{ store_result.json }}"

- name: Fetch The Email
  set_fact:
    email_list: "{{ email_list|default([]) + [item.email] }}"
    name_list: "{{ name_list|default([]) + [item.name]}}"
  loop: "{{ jsondata.data }}"

- name: Display the result emailid
  set_fact:
    email_result: "{{ email_list }}"
    name_result: "{{ name_list }}"

- name: Get Together
  set_fact:
    name_email_resut: "{{ item.0 + item.1 }}"
    with_together:
      - email_result
      - name_result

- name: Print the Email-ids
  debug:
    var: name_email_result
