---
- name: Include Vars files
  include_vars: "roles/debug-api/vars/dev_api.yml"
  no_log: true

- name: Fetch the API information
  uri:
   url: "http://restapi.adequateshop.com/api/users?page=1"
   method: GET
   body_format: json
   return_content: yes
   headers:
    Authorization: "{{ api_token }}"
    Content-Type: "application/json"
    Accept: "*/*"
   status_code: 200
  register: store_result
 # until: api_result.json.status == "200"
  #retries: 5
  #delay: 10
  no_log: True

- name: Display the result
  debug:
    var: store_result.json

- name: Set facts
  set_fact:
    jsondata: "{{ store_result.json }}"

- name: Creating Empty List
  set_fact:
    email_list: []

- name: Fetch the email
  set_fact:
    #loopsnums: "{{ item }}"
    emailid: "{{ email_list|default([]) + jsondata.data[item].email }}"
  with_items: [1,2,3]

- name: Print the Email-ids
  debug:
    msg: var=email_list
